name: Deploy based on branch

on:
  push:
    branches:
      - develop
      - main
      - vapor_CD

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-dev

      - name: Require Vapor CLI
        run: composer global require laravel/vapor-cli

      - name: Deploy to qa
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/vapor_CD'
        run: vapor deploy qa --without-waiting
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: vapor deploy production --without-waiting
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
