name: Deploy to Laravel Vapor based on branch

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Deploy to staging
        if: github.ref == 'refs/heads/develop'
        uses: teamnovu/vapor-action@master
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
        with:
          args: deploy staging

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        uses: teamnovu/vapor-action@master
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
        with:
          args: deploy production
